### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by ways2read** [ways2read/InDesignA11Y#18]
Knowledge base reference: http://kb.daisy.org/publishing/docs/metadata/evaluation.html

**Comment by LauraB7** [comment]
User story: "As an end user, librarian or teacher I can have confidence concerning the accessibility features/hazards of a publication in the retail or library catalog." "As a publisher I can document the conformance level with the EPUB accessibility specification by including accessibility metadata."

**Comment by puchchi** [comment]
Hello, we have some questions about this request. Please find them listed below.

1. "_When an assessment of a publication has been performed_". Where is this evaluation supposed to take place? Is it in InDesign before or whilte exporting EPUB?
2. How is this evaluation supposed to take place?

**Comment by gregoriopellegrino** [comment]
Dear @puchchi,
accessibility evaluation is done outside InDesign by checking the EPUB file through some automatic tools (EPUBCheck and Ace by DAISY) and through some manual checklists (e.g. SMART by DAISY). The InDesign user would then add the [appropriate metadata](http://kb.daisy.org/publishing/docs/metadata/evaluation.html) before final export.

**Comment by puchchi** [comment]
Thanks @gregoriopellegrino.
Just to be sure, it's like providing a field, during EPUB export, where InDesign user can add field like "certifiedBy" and "certifierCredential". right?

**Comment by gregoriopellegrino** [comment]
Right. The most important metadata is [dcterms:conformsTo](https://www.w3.org/TR/epub-a11y/#sec-conf-reporting-pub) which is mandatory to be compliant with the [EPUB Accessibility](https://www.w3.org/TR/epub-a11y/) specs.

[a11y:certifiedBy](https://www.w3.org/TR/epub-a11y/#certifiedBy), [a11y:certifierCredential](https://www.w3.org/TR/epub-a11y/#certifierCredential) and [a11y:certifierReport](https://www.w3.org/TR/epub-a11y/#certifierCredential) are optional since non all EPUB publications are certified by third parties.

**Comment by raman211** [comment]
Hi @ways2read , @LauraB7 , @gregoriopellegrino

This is Ramanjulu from Adobe InDesign Team. We are looking to give content creators a way to add the above accessibility and need some clarity from you all.

We have the proposed design specs available here https://xd.adobe.com/view/f296cb1f-2874-4e2f-83d4-2cf6fdc06794-a7c5/

Could you please share your feedback on the proposed designs for the same?
Thanks.

**Comment by CircularKen** [comment]
I note that this feature is not present in Adobe InDesign 2024 (19.0)

**Comment by raman211** [comment]
Hi @ways2read, @LauraB7 , @gregoriopellegrino, @CircularKen

We have released this feature as part of the pre release builds a week back and the same are available here with 
https://forums.adobeprerelease.com/indesigndev/discussion/430/rcs-builds-for-indesign-incopy-and-ids-2024-19-0-1-205-along-with-the-sdk-are-now-available#latest
https://forums.adobeprerelease.com/indesign/discussion/2377/rcs-builds-for-indesign-and-incopy-2024-19-0-1-205-builds-are-now-available-to-download#latest

Hope you have played with the feature and we are waiting to hear your feedback on it.

Thanks,
Ramanjulu.

**Comment by gregoriopellegrino** [comment]
@raman211 thank you. We have tested it and everything seems okay to us. With this release the work on this issue is concluded for us. We will close the issue once the feature is released in a public version of InDesign.

**Comment by gregoriopellegrino** [comment]
@raman211 We realized a small bug in the `Conforms to` field. If `EPUB Accessibility 1.1 - WCAG 2.1 Level AA` is selected, the value is not exported to the metadata. The other values in the drop-down menu seem to work correctly.

![image](https://github.com/ways2read/InDesignA11Y/assets/5065125/42d287d4-4168-43ea-bc73-90668bb8f078)

**Comment by gregoriopellegrino** [comment]
Dear @raman211,
to prepare ourselves for the call scheduled on Monday, June 17th: are there any new updates or releases related to this issue (specifically https://github.com/ways2read/InDesignA11Y/issues/18#issuecomment-1940592562)?

Currently, we are running the _InDesign Pre-Release 19.5 (Mainline CI #f95bd09)_ version on our machines.

Thanks

**Comment by jonaslil** [comment]
During yesterday's call, we discussed the accessibility metadata feature and reviewed issue #19.

The conformance field bug is reported above in https://github.com/ways2read/InDesignA11Y/issues/18#issuecomment-1940592562. It is significant, as the value that is not exported relates to compliance with EEA legislation, a key target for many publishers.

**Comment by jonaslil** [comment]
It’s great to see that the bug in the "Conforms to" field has been fixed in the latest prerelease (v. 20.0). All values, including `EPUB Accessibility 1.1 - WCAG 2.1 Level AA`, are now exported as expected.
